version: '3'
services:
  nsfw_image_detection:
    image: ghcr.io/tiltedcube/falconsai_nsfw_image_detection:latest
    ports:
      - "8000:8000"
    volumes:
        - ./models:/app/models:rw
    environment:
      - MODEL_NAME
      - SCORE