name: OpenCL Production CI/CD

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
    
env:
  REGISTRY: "ghcr.io"
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_SECRET: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write
   
jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            include:
              - docker_file: Dockerfile.opencl.nvidia
                label: "latest-opencl-nvidia"
              - docker_file: Dockerfile.opencl.amd.rusticl
                label: "latest-opencl-amd-rusticl"
              - docker_file: Dockerfile.opencl.amd.clover
                label: "latest-opencl-amd-clover"

        steps:
            - uses: actions/checkout@v4

            - name: Meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: |
                  type=ref,event=branch
                  type=ref,event=pr
                  type=ref,event=tag
                  type=sha,prefix=sha-
                  type=raw,value=latest,enable=${{ matrix.label == 'latest' }}
                labels: |
                  type=raw,value=image-type=${{ matrix.label }}

            - uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ env.REGISTRY_USER }}
                password: ${{ env.REGISTRY_SECRET }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ${{ matrix.docker_file }}
                push: ${{ github.event_name != 'pull_request' }}
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64